r2dbc:
  url: r2dbc:mysql://localhost:3306/todo?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
  username: user
  password: password

logging:
  level:
    io.r2dbc.pool: debug
